n_repeat: 10
data:
  data_name: "linear"  # {np, linear, demand}
  data_size: 2000  # [2000, 5000, 10000]
  m_scale: [0.5, 1., 2.]  # [0.5, 1., 2.] # times ground truth std
  n_scale: null
  bias: 0. # merror bias
  merror_func_str: "multi_gaussian_new"  # {gaussian, multi_gaussian}
train_params:
  n_epochs: 30
  batch_size: 100
  n_sample: 2
