n_repeat: 30

train_params:
  split_ratio: 0.5
  lambda_mn: [0, -10]
  lambda_n: [0, -10]
  xi: [0, -10]

  lambda_x: null
  n_chi: 500
  Chi_lim: [-0.5, 0.5]
  label_cutoff: 1.0
  reg_param: 0.
  batch_size: 64
  lr: 0.1
  num_epochs: 200

data:
  data_name: "dahl_lochner"  # {sigmoid, linear, demand}
  data_size: 2000  # [1000, 5000, 10000]
  m_scale: [None]  # [0.5, 1., 2.] # times ground truth std
  n_scale: null
  bias: 0. # merror bias
  merror_func_str: ['gaussian']  # {gaussian, multi_gaussian, uniform}
