n_repeat: 10
data:
  data_name: "demand"  # {np, linear, demand}
  data_size: 1000  # [1000, 5000, 10000]
  rho: 0.5  # [0.25, 0.5, 0.75, 0.9] # confounding level
  m_scale: 1.  # [0.5, 1., 2.] # times ground truth std
  n_scale: null
  bias: 0. # merror bias
  merror_func_str: "gaussian"  # {gaussian, multi_gaussian}
train_params:
  lambda: [0, -10]
  xi: [0, -10]
  split_ratio: 0.5

